CREATE TABLE [dbo].[Area]
(
	[ID] INT CONSTRAINT PK_Area PRIMARY KEY CLUSTERED (ID),
	[Description] VARCHAR(10) NOT NULL,
	[EffectiveDate] DATETIME NOT NULL CONSTRAINT DF_Area_EffectiveDate DEFAULT(GETDATE()),
	[DateLastUpdated] DATETIME NOT NULL CONSTRAINT DF_Area_DateLastUpdated DEFAULT(GETDATE()),
	[UserIDLastUpdated] BIGINT NOT NULL CONSTRAINT DF_Area_UserIDLastUpdated DEFAULT(0)
)
