CREATE TABLE [dbo].[Part](
	[ID] INT NOT NULL,
	[HondaCode] VARCHAR(20) NULL,
	[PartNumber] VARCHAR(20) NULL,
	[PartDescription] VARCHAR(130) NULL,
	[PartControlCode] VARCHAR(15) NULL,
	[SRACode] VARCHAR(7) NULL,
	[MostForwardSupersession] VARCHAR(23) NULL,
	[ForwardSupersession] VARCHAR(23) NULL,
	[BackwardSupersession] VARCHAR(23) NULL,
	[MultiOrderQuantity] INT NULL,
	[DealerNetPriceAmount] NUMERIC(18, 2) NULL,
	[SuggestedRetailPriceAmount] NUMERIC(18, 2) NULL,
	[CoreCostAmount] NUMERIC(18, 2) NULL,
	[PriceChangeFlag] VARCHAR(15) NULL,
	[PartStatusCode] VARCHAR(15) NULL,
	[VDFlag] VARCHAR(1) NULL,
	[WholsaleCompFlag] VARCHAR(1) NULL,
	[PartModificationCode] VARCHAR(1) NULL,
	[NATABCQuantityCode] VARCHAR(1) NULL,
	[PartSizeCode] VARCHAR(5) NULL,
	[CRSShipCode] VARCHAR(5) NULL,
	[CommonPartFlag] VARCHAR(5) NULL,
	[Weight] VARCHAR(10) NULL,
	[Height] VARCHAR(10) NULL,
	[Length] VARCHAR(10) NULL,
	[PartNumberStripped] VARCHAR(20) NULL,
	[Width] VARCHAR(10) NULL,
	[PartColorDescription] VARCHAR(100) NULL,
	[PartColorName] VARCHAR(30) NULL
)
GO
CREATE CLUSTERED INDEX IX_Part
ON [dbo].[Part]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO
CREATE NONCLUSTERED INDEX IX_Part_PartNumber
ON [dbo].[Part]
(
	[PartNumber]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO
CREATE NONCLUSTERED INDEX IX_Part_HondaCode_PartNumber
ON [dbo].[Part]
(
	[HondaCode],
	[PartNumber]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO
CREATE NONCLUSTERED INDEX IX_Part_PartNumberStripped_PartNumber
ON [dbo].[Part]
(
	[PartNumberStripped],
	[PartNumber]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO
CREATE NONCLUSTERED INDEX IX_Part_PartDescription
ON [dbo].[Part]
(
	[PartDescription]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO