CREATE TABLE [dbo].[Year]
(
	[ID] INT CONSTRAINT PK_Year PRIMARY KEY CLUSTERED (ID),
	[Description] VARCHAR(10) NOT NULL,
	[VinCode] VARCHAR(1) NULL,
	[EffectiveDate] DATETIME NOT NULL CONSTRAINT DF_Year_EffectiveDate DEFAULT(GETDATE()),
	[DateLastUpdated] DATETIME NOT NULL CONSTRAINT DF_Year_DateLastUpdated DEFAULT(GETDATE()),
	[UserIDLastUpdated] BIGINT NOT NULL CONSTRAINT DF_Year_UserIDLastUpdated DEFAULT(0)
)
