# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/spare-parts-web" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/spare-parts-dashboard" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/spare-parts-api/SpareParts.Api" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/spare-parts-api/SpareParts.AppService" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/spare-parts-api/SpareParts.Data" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/spare-parts-api/SpareParts.Domain" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/spare-parts-database/SparePartsData" # Location of package manifests
    schedule:
      interval: "weekly"
