CREATE TABLE [dbo].[User] (
    [Id]                   BIGINT        IDENTITY (1, 1) NOT NULL,
    [FirstName]            VARCHAR (50)  NOT NULL,
    [LastName]             VARCHAR (50)  NOT NULL,
    [Email]                VARCHAR (100) NOT NULL,
    [Password]             VARCHAR (255) NOT NULL,
    [Role]                 VARCHAR (10)  NOT NULL,
    [VerificationCode]     VARCHAR (255) NOT NULL,
    [Verified]             BIT           NOT NULL,
    [PasswordResetToken]   VARCHAR (255) NULL,
    [PasswordResetExpires] DATETIME      NULL,
    [Phone]                VARCHAR (50)  NULL,
    [Active]               BIT           NOT NULL,
    [Theme]                VARCHAR(10)   NULL,
    [CreatedBy]            BIGINT        NULL,
    [CreatedOn]            DATETIME      NULL,
    [ModifiedBy]           BIGINT        NULL,
    [ModifiedOn]           DATETIME      NULL,
    CONSTRAINT PK_User PRIMARY KEY  CLUSTERED ([Id] ASC),
    CONSTRAINT U_Email UNIQUE  NONCLUSTERED ([Email]),
);